max_vel_x: 0.45
min_vel_x: 0.1
max_vel_y: 0.45
min_vel_y: 0.1
max_rotational_vel: 0.4
min_in_place_rotational_vel: 0.1

acc_lim_theta: 3.2
acc_lim_x: 2.5
acc_lim_y: 2.5

holonomic_robot: true

controller_frequency: 5
